// BlurrySite Perf — 00-baseline: page-load metrics with extension idle

'use strict';

const { test, expect, setModel, resetModel } = require('../fixtures/extension');
const { setupWebVitals, collectHeap, summarize, trackContentScriptReady, waitForContentScript } = require('../shared/metrics');
const fs = require('fs');
const path = require('path');

// perf-baseline.json — generated by scripts/generate-baseline.js after a data collection run.
// Falls back to hardcoded values when baseline doesn't exist (first run or CI cold start).
const _baseline = (() => {
  try { return require('../reports/perf-baseline.json'); } catch (_) { return {}; }
})();
const budget = (key, fallback) => _baseline[key] != null ? _baseline[key] : fallback;

const FIXTURE_PAGE_IDS = [
  'text-heavy',
  'pii-rich',
  'comprehensive',
  'reveal',
  'picker',
  'spa',
  'forms',
  'media',
];

// FCP ceiling per fixture (ms). Extension is idle — any value above this means
// content script init has regressed to the point of delaying first paint.
// Chosen conservatively: 2× what a minimal static page renders in headed Chrome.
const FCP_BUDGET = {
  'text-heavy':   3000,
  'pii-rich':     3000,
  'comprehensive':3500,
  'reveal':       2500,
  'picker':       2500,
  'spa':          2500,
  'forms':        2500,
  'media':        3000,
};

let results = [];

test.beforeAll(async ({ extSw }) => {
  await resetModel(extSw);
  await setModel(extSw, {
    blur_all: { status: false },
    auto_detect_pii: { status: false, settings: { email: false, numeric: false } },
  });
});

for (const pageId of FIXTURE_PAGE_IDS) {
  test(`baseline: ${pageId}`, async ({ extContext, fixtureUrl }) => {
    const page = await extContext.newPage();

    const collectVitals = await setupWebVitals(page);
    await trackContentScriptReady(page);

    await page.goto(fixtureUrl(pageId), { waitUntil: 'load' });
    await waitForContentScript(page);

    const vitals = await collectVitals();
    const heap = await collectHeap(page);
    const blurredCount = await page.evaluate(
      () => document.querySelectorAll('.bl-si-blurred').length
    );

    console.log(
      `[baseline:${pageId}] FCP=${vitals.fcp?.toFixed(0)}ms LCP=${vitals.lcp?.toFixed(0)}ms CLS=${vitals.cls?.toFixed(4)} INP=${vitals.inp != null ? vitals.inp + 'ms' : 'n/a'} heap=${heap ? (heap.used / 1024 / 1024).toFixed(1) + 'MB' : 'n/a'} blurred=${blurredCount}`
    );

    await page.close();

    results.push({
      pageId,
      fcp: vitals.fcp ?? null,
      lcp: vitals.lcp ?? null,
      cls: vitals.cls ?? null,
      inp: vitals.inp ?? null,
      inp_count: vitals.inp_count ?? 0,
      heapUsedMB: heap ? heap.used / 1024 / 1024 : null,
      blurredCount,
    });

    expect(blurredCount).toBe(0);
    // Idle-tax guard: FCP must not regress beyond budget even with extension loaded but inactive.
    // A null FCP means the observer missed the entry — treat as a skip, not a failure.
    if (vitals.fcp != null) {
      expect(vitals.fcp).toBeLessThan(budget(`fcp.${pageId}.budget_ms`, FCP_BUDGET[pageId]));
    }

    // INP assertion: only when interactions were recorded (page had user events)
    // Baseline pages are navigation-only, so inp_count is usually 0. Assert when present.
    if (vitals.inp != null && vitals.inp_count > 0) {
      expect(vitals.inp).toBeLessThan(budget('inp.baseline.max_ms', 200));
    }
  });
}

test.afterAll(async () => {
  const reportsDir = path.resolve(__dirname, '../reports');
  if (!fs.existsSync(reportsDir)) fs.mkdirSync(reportsDir, { recursive: true });
  fs.writeFileSync(
    path.join(reportsDir, '00-baseline-raw.json'),
    JSON.stringify({ timestamp: new Date().toISOString(), results }, null, 2)
  );
});
