// BlurrySite Perf — 01-blur-all: activation latency on text-heavy + comprehensive

'use strict';

const { test, expect, setModel, resetModel } = require('../fixtures/extension');
const { waitForBlurred, summarize, trackContentScriptReady, waitForContentScript, collectHeap, computeHeapSlope } = require('../shared/metrics');
const fs = require('fs');
const path = require('path');

// perf-baseline.json — generated by scripts/generate-baseline.js after a data collection run.
// Falls back to hardcoded values when baseline doesn't exist (first run or CI cold start).
const _baseline = (() => {
  try { return require('../reports/perf-baseline.json'); } catch (_) { return {}; }
})();
const budget = (key, fallback) => _baseline[key] != null ? _baseline[key] : fallback;

let textHeavyResults;
let comprehensiveResults;

test.beforeAll(async ({ extSw }) => {
  await resetModel(extSw);
});

// ---------------------------------------------------------------------------
// Test 1: blur-all activation on text-heavy page
//
// Target: page-text-heavy.html (2000 paragraphs, 800 spans, 100 code, financial table)
// Threshold: ≥ 500 .bl-si-blurred elements (page reaches 2000+ eventually)
// Iterations: 50 measured (n≥50 required for statistically valid p95)
// Budget: p95 < 300ms
// ---------------------------------------------------------------------------
test('blur-all: activation on text-heavy', async ({ extContext, extSw, fixtureUrl }) => {
  const page = await extContext.newPage();

  // Start with blur OFF
  await setModel(extSw, { blur_all: { status: false } });
  await trackContentScriptReady(page);
  await page.goto(fixtureUrl('text-heavy'), { waitUntil: 'load' });
  await waitForContentScript(page);

  const durations = [];
  const counts = [];
  const heapSamples = [];

  for (let i = 0; i < 50; i++) {
    // Reset: turn blur off, then wait until all blurred elements are actually cleared.
    // Fixed timeouts are unreliable — 2000-element teardown can exceed 300ms.
    await setModel(extSw, { blur_all: { status: false } });
    await page.waitForFunction(
      () => document.querySelectorAll('.bl-si-blurred').length === 0,
      { timeout: 5000, polling: 4 }
    );

    // Start measurement BEFORE trigger so t0 is captured before storage.onChanged fires
    const measurePromise = waitForBlurred(page, 500);

    // Trigger: turn blur on
    await setModel(extSw, { blur_all: { status: true } });

    // Wait for threshold
    const result = await measurePromise;
    durations.push(result.durationMs);
    counts.push(result.count);

    const heapMb = await collectHeap(page);
    heapSamples.push(heapMb ? heapMb.used / 1024 / 1024 : null);
  }

  const stats = summarize(durations);
  console.log(
    `[blur-all:text-heavy] p50=${stats.p50}ms p95=${stats.p95}ms max=${stats.max}ms count_avg=${Math.round(counts.reduce((s, v) => s + v, 0) / counts.length)}`
  );

  // Budget assertion
  expect(stats.p95).toBeLessThan(budget('blur_all.text-heavy.p95_ms', 300));

  const heapSlope = computeHeapSlope(heapSamples);
  console.log(`[blur-all:text-heavy] heap_slope=${heapSlope != null ? heapSlope.toFixed(3) : 'n/a'} MB/iteration`);
  // A positive slope > 0.1 MB/iteration indicates a memory leak under repeated blur operations.
  if (heapSlope != null) {
    expect(heapSlope).toBeLessThan(budget('heap.blur_all.slope_mb_per_iter', 0.1));
  }

  // Accumulate into module-level results for afterAll
  textHeavyResults = {
    page: 'text-heavy',
    threshold: 500,
    iterations: 50,
    durations,
    stats,
    heapSamples,
    heapSlope,
  };

  await page.close();
});

// ---------------------------------------------------------------------------
// Test 2: blur-all activation on comprehensive page
//
// Target: page-comprehensive.html (all 5 categories: 400 text + 70 media +
//         130 form + 320 table cells + 50 structure)
// Threshold: ≥ 200 .bl-si-blurred (comprehensive has fewer pure-blur-eligible elements)
// Iterations: 50 measured (n≥50 required for statistically valid p95)
// Budget: p95 < 500ms (more element types = more work)
// ---------------------------------------------------------------------------
test('blur-all: activation on comprehensive', async ({ extContext, extSw, fixtureUrl }) => {
  const page = await extContext.newPage();

  // Start with blur OFF
  await setModel(extSw, { blur_all: { status: false } });
  await trackContentScriptReady(page);
  await page.goto(fixtureUrl('comprehensive'), { waitUntil: 'load' });
  await waitForContentScript(page);

  const durations = [];
  const counts = [];
  const heapSamples = [];

  for (let i = 0; i < 50; i++) {
    // Reset: turn blur off, then wait until all blurred elements are actually cleared.
    await setModel(extSw, { blur_all: { status: false } });
    await page.waitForFunction(
      () => document.querySelectorAll('.bl-si-blurred').length === 0,
      { timeout: 5000, polling: 4 }
    );

    // Start measurement BEFORE trigger so t0 is captured before storage.onChanged fires
    const measurePromise = waitForBlurred(page, 200);

    // Trigger: turn blur on
    await setModel(extSw, { blur_all: { status: true } });

    // Wait for threshold
    const result = await measurePromise;
    durations.push(result.durationMs);
    counts.push(result.count);

    const heapMb = await collectHeap(page);
    heapSamples.push(heapMb ? heapMb.used / 1024 / 1024 : null);
  }

  const stats = summarize(durations);
  console.log(
    `[blur-all:comprehensive] p50=${stats.p50}ms p95=${stats.p95}ms max=${stats.max}ms count_avg=${Math.round(counts.reduce((s, v) => s + v, 0) / counts.length)}`
  );

  // Budget assertion
  expect(stats.p95).toBeLessThan(budget('blur_all.comprehensive.p95_ms', 500));

  const heapSlope = computeHeapSlope(heapSamples);
  console.log(`[blur-all:comprehensive] heap_slope=${heapSlope != null ? heapSlope.toFixed(3) : 'n/a'} MB/iteration`);
  // A positive slope > 0.1 MB/iteration indicates a memory leak under repeated blur operations.
  if (heapSlope != null) {
    expect(heapSlope).toBeLessThan(budget('heap.blur_all.slope_mb_per_iter', 0.1));
  }

  // Accumulate into module-level results for afterAll
  comprehensiveResults = {
    page: 'comprehensive',
    threshold: 200,
    iterations: 50,
    durations,
    stats,
    heapSamples,
    heapSlope,
  };

  await page.close();
});

// ---------------------------------------------------------------------------
// afterAll — write both results to reports/01-blur-all-raw.json
// ---------------------------------------------------------------------------
test.afterAll(async () => {
  const reportsDir = path.resolve(__dirname, '../reports');
  if (!fs.existsSync(reportsDir)) fs.mkdirSync(reportsDir, { recursive: true });

  fs.writeFileSync(
    path.join(reportsDir, '01-blur-all-raw.json'),
    JSON.stringify(
      {
        timestamp: new Date().toISOString(),
        tests: [
          textHeavyResults ?? null,
          comprehensiveResults ?? null,
        ],
      },
      null,
      2
    )
  );
});
