// BlurrySite Perf — 02-pii-scan: PII detector throughput on pii-rich fixture

'use strict';

const { test, expect, setModel, resetModel } = require('../fixtures/extension');
const { waitForPii, summarize, trackContentScriptReady, waitForContentScript } = require('../shared/metrics');
const fs = require('fs');
const path = require('path');

// perf-baseline.json — generated by scripts/generate-baseline.js after a data collection run.
// Falls back to hardcoded values when baseline doesn't exist (first run or CI cold start).
const _baseline = (() => {
  try { return require('../reports/perf-baseline.json'); } catch (_) { return {}; }
})();
const budget = (key, fallback) => _baseline[key] != null ? _baseline[key] : fallback;

// Module-scope result containers — populated by each test, written out in afterAll.
let emailNumericResults;
let emailOnlyResults;
let sectionResults;

test.beforeAll(async ({ extSw }) => {
  await resetModel(extSw);
});

// ---------------------------------------------------------------------------
// Test 1: email + numeric detection on the full pii-rich page
// ---------------------------------------------------------------------------
test('pii-scan: email + numeric on pii-rich', async ({ extContext, extSw, fixtureUrl }) => {
  const page = await extContext.newPage();

  // Start with PII off
  await setModel(extSw, { auto_detect_pii: { status: false, settings: { email: false, numeric: false } } });
  await trackContentScriptReady(page);
  await page.goto(fixtureUrl('pii-rich'), { waitUntil: 'load' });
  await waitForContentScript(page);

  const durations = [];
  const counts = [];

  for (let i = 0; i < 50; i++) {
    // Reset: turn PII off, wait until all PII spans are actually removed
    await setModel(extSw, { auto_detect_pii: { status: false, settings: { email: false, numeric: false } } });
    await page.waitForFunction(
      () => document.querySelectorAll('[data-bl-si-pii]').length === 0,
      { timeout: 5000, polling: 4 }
    );

    // Start measurement BEFORE trigger so t0 is captured before storage.onChanged fires
    const measurePromise = waitForPii(page, 500);

    // Trigger: enable both types
    await setModel(extSw, { auto_detect_pii: { status: true, settings: { email: true, numeric: true } } });

    // Wait for threshold
    const result = await measurePromise;
    durations.push(result.durationMs);
    counts.push(result.count);
  }

  const stats = summarize(durations);
  console.log(
    `[pii-scan:email+numeric] p50=${stats.p50}ms p95=${stats.p95}ms max=${stats.max}ms count_avg=${Math.round(counts.reduce((s, v) => s + v, 0) / counts.length)}`
  );

  expect(stats.p95).toBeLessThan(budget('pii.email_numeric.p95_ms', 1000));

  // One-shot storage propagation delay measurement (not in the hot loop)
  // Measures: time from setModel() call → first [data-bl-si-pii] span appears.
  // This is the full round-trip: Node → CDP → SW → storage → content script → DOM.
  {
    await setModel(extSw, { auto_detect_pii: { status: false, settings: { email: false, numeric: false } } });
    await page.waitForFunction(
      () => document.querySelectorAll('[data-bl-si-pii]').length === 0,
      { timeout: 5000, polling: 4 }
    );
    const propT0 = Date.now();
    await setModel(extSw, { auto_detect_pii: { status: true, settings: { email: true, numeric: true } } });
    await page.waitForFunction(
      () => document.querySelectorAll('[data-bl-si-pii]').length >= 1,
      { timeout: 10000, polling: 4 }
    );
    const storagePropMs = Date.now() - propT0;
    console.log(`[pii-scan] storage_propagation_ms=${storagePropMs}ms (setModel → first PII span)`);
    emailNumericResults = { pattern: 'email+numeric', threshold: 500, iterations: 50, durations, stats, storagePropMs };
  }

  await page.close();
});

// ---------------------------------------------------------------------------
// Test 2: email-only detection on the full pii-rich page
// ---------------------------------------------------------------------------
test('pii-scan: email only on pii-rich', async ({ extContext, extSw, fixtureUrl }) => {
  const page = await extContext.newPage();

  // Start with PII off
  await setModel(extSw, { auto_detect_pii: { status: false, settings: { email: false, numeric: false } } });
  await trackContentScriptReady(page);
  await page.goto(fixtureUrl('pii-rich'), { waitUntil: 'load' });
  await waitForContentScript(page);

  const durations = [];
  const counts = [];

  for (let i = 0; i < 50; i++) {
    // Reset: turn PII off, wait until all PII spans are actually removed
    await setModel(extSw, { auto_detect_pii: { status: false, settings: { email: false, numeric: false } } });
    await page.waitForFunction(
      () => document.querySelectorAll('[data-bl-si-pii]').length === 0,
      { timeout: 5000, polling: 4 }
    );

    // Start measurement BEFORE trigger so t0 is captured before storage.onChanged fires
    const measurePromise = waitForPii(page, 300);

    // Trigger: enable email only
    await setModel(extSw, { auto_detect_pii: { status: true, settings: { email: true, numeric: false } } });

    // Wait for threshold (emails only — subset of full scan)
    const result = await measurePromise;
    durations.push(result.durationMs);
    counts.push(result.count);
  }

  const stats = summarize(durations);
  console.log(
    `[pii-scan:email-only] p50=${stats.p50}ms p95=${stats.p95}ms max=${stats.max}ms count_avg=${Math.round(counts.reduce((s, v) => s + v, 0) / counts.length)}`
  );

  expect(stats.p95).toBeLessThan(budget('pii.email_only.p95_ms', 600));

  emailOnlyResults = { pattern: 'email-only', threshold: 300, iterations: 50, durations, stats };
  await page.close();
});

// ---------------------------------------------------------------------------
// Test 3: section-a vs section-b isolation — verify detection coverage per section
// ---------------------------------------------------------------------------
test('pii-scan: section-a vs section-b isolation', async ({ extContext, extSw, fixtureUrl }) => {
  const page = await extContext.newPage();

  await setModel(extSw, { auto_detect_pii: { status: false, settings: { email: false, numeric: false } } });
  await trackContentScriptReady(page);
  await page.goto(fixtureUrl('pii-rich'), { waitUntil: 'load' });
  await waitForContentScript(page);

  await setModel(extSw, { auto_detect_pii: { status: true, settings: { email: true, numeric: true } } });

  // Wait for detection to complete
  const result = await waitForPii(page, 500);

  // Count per section
  const sectionCounts = await page.evaluate(() => ({
    sectionA: document.querySelector('#section-a')?.querySelectorAll('[data-bl-si-pii]').length ?? 0,
    sectionB: document.querySelector('#section-b')?.querySelectorAll('[data-bl-si-pii]').length ?? 0,
    total: document.querySelectorAll('[data-bl-si-pii]').length,
  }));

  console.log(
    `[pii-scan:sections] A=${sectionCounts.sectionA} B=${sectionCounts.sectionB} total=${sectionCounts.total} in ${result.durationMs}ms`
  );

  // Section A should have isolated spans detected
  expect(sectionCounts.sectionA).toBeGreaterThan(100);
  // Section B should also have detections
  expect(sectionCounts.sectionB).toBeGreaterThan(100);

  sectionResults = sectionCounts;
  await page.close();
});

// ---------------------------------------------------------------------------
// afterAll — write all collected results to the reports directory
// ---------------------------------------------------------------------------
test.afterAll(async () => {
  const reportsDir = path.resolve(__dirname, '../reports');
  if (!fs.existsSync(reportsDir)) fs.mkdirSync(reportsDir, { recursive: true });
  fs.writeFileSync(
    path.join(reportsDir, '02-pii-raw.json'),
    JSON.stringify(
      {
        timestamp: new Date().toISOString(),
        emailNumericResults: emailNumericResults ?? null,
        emailOnlyResults: emailOnlyResults ?? null,
        sectionResults: sectionResults ?? null,
      },
      null,
      2
    )
  );
});
