// BlurrySite Perf — 03-picker: picker activation latency via keyboard shortcut

'use strict';

const { test, expect, setModel, resetModel } = require('../fixtures/extension');
const { waitForClass, summarize, trackContentScriptReady, waitForContentScript } = require('../shared/metrics');
const fs = require('fs');
const path = require('path');

// perf-baseline.json — generated by scripts/generate-baseline.js after a data collection run.
// Falls back to hardcoded values when baseline doesn't exist (first run or CI cold start).
const _baseline = (() => {
  try { return require('../reports/perf-baseline.json'); } catch (_) { return {}; }
})();
const budget = (key, fallback) => _baseline[key] != null ? _baseline[key] : fallback;

// Accumulated results written out in afterAll
let pickerActivationResults = null;
let pickerBlurAllResults = null;
let pickerScrollResults = null;

test.beforeAll(async ({ extSw }) => {
  await resetModel(extSw);
});

// ---------------------------------------------------------------------------
// Helper: ensure picker is OFF (not active) before measuring activation.
// If the picker is already active, press the shortcut once to deactivate it
// and wait for the class to disappear.
// ---------------------------------------------------------------------------
async function ensurePickerOff(page) {
  const isActive = await page.evaluate(
    () => document.documentElement.classList.contains('bl-si-picker-active')
  );
  if (isActive) {
    await page.keyboard.press('Alt+Shift+P');
    await page.waitForFunction(
      () => !document.documentElement.classList.contains('bl-si-picker-active'),
      { timeout: 5000 }
    );
    await page.waitForTimeout(100);
  }
}

// ---------------------------------------------------------------------------
// Test 1 — activation latency (keyboard shortcut, no blur-all)
// ---------------------------------------------------------------------------
test('picker: activation latency (keyboard shortcut)', async ({ extContext, extSw, fixtureUrl }) => {
  const page = await extContext.newPage();

  await setModel(extSw, { blur_all: { status: false } });
  await trackContentScriptReady(page);
  await page.goto(fixtureUrl('picker'), { waitUntil: 'load' });
  await waitForContentScript(page);

  // Click the page to ensure it has focus (keyboard events need focus)
  await page.click('body');

  const activationDurations = [];
  const deactivationDurations = [];

  for (let i = 0; i < 30; i++) {
    // Ensure picker is OFF before measuring activation
    await ensurePickerOff(page);

    // Measure activation — start measuring BEFORE pressing the key
    const activatePromise = waitForClass(page, 'html', 'bl-si-picker-active', { timeout: 5000 });
    await page.keyboard.press('Alt+Shift+P');
    const activateResult = await activatePromise;
    activationDurations.push(activateResult.durationMs);

    await page.waitForTimeout(100);

    // Measure deactivation — picker is now ON; measure time until class disappears
    const deactivatePromise = page.waitForFunction(
      () => !document.documentElement.classList.contains('bl-si-picker-active'),
      { timeout: 5000 }
    );
    const t0 = await page.evaluate(() => performance.now());
    await page.keyboard.press('Alt+Shift+P');
    await deactivatePromise;
    const deactivateDuration = await page.evaluate(
      (start) => Math.round(performance.now() - start),
      t0
    );
    deactivationDurations.push(deactivateDuration);

    await page.waitForTimeout(100);
  }

  const activateStats = summarize(activationDurations);
  const deactivateStats = summarize(deactivationDurations);

  console.log(
    `[picker:activation] p50=${activateStats.p50}ms p95=${activateStats.p95}ms max=${activateStats.max}ms`
  );
  console.log(
    `[picker:deactivation] p50=${deactivateStats.p50}ms p95=${deactivateStats.p95}ms max=${deactivateStats.max}ms`
  );

  expect(activateStats.p95).toBeLessThan(budget('picker.activation.p95_ms', 150));

  pickerActivationResults = {
    activationDurations,
    activateStats,
    deactivationDurations,
    deactivateStats,
  };

  await page.close();
});

// ---------------------------------------------------------------------------
// Test 2 — activation with blur-all active
// ---------------------------------------------------------------------------
test('picker: activation with blur-all active', async ({ extContext, extSw, fixtureUrl }) => {
  const page = await extContext.newPage();

  await setModel(extSw, { blur_all: { status: true } });
  await trackContentScriptReady(page);
  await page.goto(fixtureUrl('picker'), { waitUntil: 'load' });
  await waitForContentScript(page);

  // Wait for blur-all to take effect — at least 10 elements must be blurred
  await page.waitForFunction(
    () => document.querySelectorAll('.bl-si-blurred').length > 10,
    { timeout: 15000 }
  );

  // Click the page to ensure it has focus
  await page.click('body');

  const activationDurations = [];
  const deactivationDurations = [];

  for (let i = 0; i < 30; i++) {
    // Ensure picker is OFF before measuring activation
    await ensurePickerOff(page);

    // Measure activation
    const activatePromise = waitForClass(page, 'html', 'bl-si-picker-active', { timeout: 5000 });
    await page.keyboard.press('Alt+Shift+P');
    const activateResult = await activatePromise;
    activationDurations.push(activateResult.durationMs);

    await page.waitForTimeout(100);

    // Measure deactivation
    const deactivatePromise = page.waitForFunction(
      () => !document.documentElement.classList.contains('bl-si-picker-active'),
      { timeout: 5000 }
    );
    const t0 = await page.evaluate(() => performance.now());
    await page.keyboard.press('Alt+Shift+P');
    await deactivatePromise;
    const deactivateDuration = await page.evaluate(
      (start) => Math.round(performance.now() - start),
      t0
    );
    deactivationDurations.push(deactivateDuration);

    await page.waitForTimeout(100);
  }

  const activateStats = summarize(activationDurations);
  const deactivateStats = summarize(deactivationDurations);

  console.log(
    `[picker:blur-all:activation] p50=${activateStats.p50}ms p95=${activateStats.p95}ms max=${activateStats.max}ms`
  );
  console.log(
    `[picker:blur-all:deactivation] p50=${deactivateStats.p50}ms p95=${deactivateStats.p95}ms max=${deactivateStats.max}ms`
  );

  // Slightly higher budget due to blurred DOM overhead
  expect(activateStats.p95).toBeLessThan(budget('picker.blur_all.activation.p95_ms', 200));

  pickerBlurAllResults = {
    activationDurations,
    activateStats,
    deactivationDurations,
    deactivateStats,
  };

  await page.close();
});

// ---------------------------------------------------------------------------
// Test 3 — page scroll does not affect activation latency
// ---------------------------------------------------------------------------
test('picker: page scroll does not affect activation', async ({ extContext, extSw, fixtureUrl }) => {
  const page = await extContext.newPage();

  await setModel(extSw, { blur_all: { status: false } });
  await trackContentScriptReady(page);
  await page.goto(fixtureUrl('picker'), { waitUntil: 'load' });
  await waitForContentScript(page);

  // Scroll to bottom of the 3500px tall page
  await page.evaluate(() => window.scrollTo(0, 3000));
  await page.waitForTimeout(200); // allow scroll to settle

  // Click the page to ensure it has focus
  await page.click('body');

  const activationDurations = [];

  for (let i = 0; i < 20; i++) {
    // Ensure picker is OFF before measuring activation
    await ensurePickerOff(page);

    // Measure activation from scrolled position
    const activatePromise = waitForClass(page, 'html', 'bl-si-picker-active', { timeout: 5000 });
    await page.keyboard.press('Alt+Shift+P');
    const activateResult = await activatePromise;
    activationDurations.push(activateResult.durationMs);

    await page.waitForTimeout(100);

    // Deactivate before next iteration (no measurement needed)
    await page.keyboard.press('Alt+Shift+P');
    await page.waitForFunction(
      () => !document.documentElement.classList.contains('bl-si-picker-active'),
      { timeout: 5000 }
    );
    await page.waitForTimeout(100);
  }

  const activateStats = summarize(activationDurations);

  console.log(
    `[picker:scrolled:activation] p50=${activateStats.p50}ms p95=${activateStats.p95}ms max=${activateStats.max}ms`
  );

  // Scroll position should not affect shortcut latency
  expect(activateStats.p95).toBeLessThan(budget('picker.scroll.activation.p95_ms', 150));

  pickerScrollResults = {
    activationDurations,
    activateStats,
  };

  await page.close();
});

// ---------------------------------------------------------------------------
// afterAll — write raw results to reports/
// ---------------------------------------------------------------------------
test.afterAll(async () => {
  const reportsDir = path.resolve(__dirname, '../reports');
  if (!fs.existsSync(reportsDir)) fs.mkdirSync(reportsDir, { recursive: true });

  fs.writeFileSync(
    path.join(reportsDir, '03-picker-raw.json'),
    JSON.stringify(
      {
        timestamp: new Date().toISOString(),
        pickerActivation: pickerActivationResults,
        pickerBlurAll: pickerBlurAllResults,
        pickerScroll: pickerScrollResults,
      },
      null,
      2
    )
  );
});
