// BlurrySite Perf — 04-spa-nav: MutationObserver reconcile per SPA route change

'use strict';

const { test, expect, setModel, resetModel } = require('../fixtures/extension');
const { waitForBlurred, summarize, trackContentScriptReady, waitForContentScript } = require('../shared/metrics');
const fs = require('fs');
const path = require('path');

// perf-baseline.json — generated by scripts/generate-baseline.js after a data collection run.
// Falls back to hardcoded values when baseline doesn't exist (first run or CI cold start).
const _baseline = (() => {
  try { return require('../reports/perf-baseline.json'); } catch (_) { return {}; }
})();
const budget = (key, fallback) => _baseline[key] != null ? _baseline[key] : fallback;

// ---------------------------------------------------------------------------
// Route thresholds — minimum .bl-si-blurred elements to wait for per route
// ---------------------------------------------------------------------------
const ROUTE_THRESHOLDS = {
  text:  200,  // 500 p + 20 h2 + 50 h3
  forms: 40,   // 100 inputs + 40 selects (FORM category)
  table: 100,  // table + td elements (TABLE category)
  media: 30,   // 60 img (MEDIA category)
  mixed: 80,   // mixed categories
};

// ---------------------------------------------------------------------------
// Route budget keys — maps route name → baseline key and fallback ms
// ---------------------------------------------------------------------------
const ROUTE_BUDGET_KEYS = {
  text:  { key: 'spa.text.p95_ms',  fallback: 400  },
  forms: { key: 'spa.forms.p95_ms', fallback: 200  },
  table: { key: 'spa.table.p95_ms', fallback: 1000 },
  media: { key: 'spa.media.p95_ms', fallback: 200  },
  mixed: { key: 'spa.mixed.p95_ms', fallback: 300  },
};

// ---------------------------------------------------------------------------
// Module-level state — accumulated across tests for afterAll report
// ---------------------------------------------------------------------------
const routeResults = {};

// ---------------------------------------------------------------------------
// beforeAll — enable blur-all so content script is actively reconciling
// ---------------------------------------------------------------------------
test.beforeAll(async ({ extSw }) => {
  await resetModel(extSw);
  await setModel(extSw, { blur_all: { status: true } });
});

// ---------------------------------------------------------------------------
// One test per SPA route
// ---------------------------------------------------------------------------
for (const route of ['text', 'forms', 'table', 'media', 'mixed']) {
  test(`spa-nav: blur reconcile on '${route}' route`, async ({ extContext, extSw, fixtureUrl }) => {
    const page = await extContext.newPage();

    // Navigate to spa page with blur-all active
    await trackContentScriptReady(page);
    await page.goto(fixtureUrl('spa'), { waitUntil: 'load' });
    await waitForContentScript(page);

    // Wait for initial route (text) to be blurred before doing anything
    await page.waitForFunction(
      () => document.querySelectorAll('.bl-si-blurred').length > 10,
      { timeout: 15000 }
    );

    // Warm-up pass: navigate away from the initial route once before measuring
    const warmupRoute = route === 'text' ? 'media' : 'text';
    await page.evaluate((r) => window.navigateTo(r), warmupRoute);
    await page.waitForTimeout(500);

    const durations = [];
    const counts = [];

    for (let i = 0; i < 20; i++) {
      // Navigate away to reset DOM to a different route
      const awayRoute = route === 'text' ? 'media' : 'text';
      await page.evaluate((r) => window.navigateTo(r), awayRoute);
      await page.waitForTimeout(300);

      // Start timing BEFORE navigation so waitForBlurred captures the full
      // MutationObserver reconcile latency from the moment navigateTo fires
      const threshold = ROUTE_THRESHOLDS[route];
      const measurePromise = waitForBlurred(page, threshold, { timeout: 30000 });
      await page.evaluate((r) => window.navigateTo(r), route);

      const result = await measurePromise;
      durations.push(result.durationMs);
      counts.push(result.count);
    }

    const stats = summarize(durations);
    console.log(
      `[spa-nav:${route}] p50=${stats.p50}ms p95=${stats.p95}ms max=${stats.max}ms count_avg=${Math.round(counts.reduce((s, v) => s + v, 0) / counts.length)}`
    );

    // Budget assertion
    const { key, fallback } = ROUTE_BUDGET_KEYS[route];
    expect(stats.p95).toBeLessThan(budget(key, fallback));

    routeResults[route] = {
      threshold: ROUTE_THRESHOLDS[route],
      iterations: 20,
      durations,
      stats,
    };

    await page.close();
  });
}

// ---------------------------------------------------------------------------
// afterAll — write all route results to reports/04-spa-raw.json
// ---------------------------------------------------------------------------
test.afterAll(async () => {
  const reportsDir = path.resolve(__dirname, '../reports');
  if (!fs.existsSync(reportsDir)) fs.mkdirSync(reportsDir, { recursive: true });
  fs.writeFileSync(
    path.join(reportsDir, '04-spa-raw.json'),
    JSON.stringify({ timestamp: new Date().toISOString(), routes: routeResults }, null, 2)
  );
});
