// BlurrySite Perf — 05-reveal: reveal controller hover/un-reveal latency

'use strict';

const { test, expect, setModel, resetModel } = require('../fixtures/extension');
const { waitForAttr, summarize } = require('../shared/metrics');
const fs = require('fs');
const path = require('path');

// perf-baseline.json — generated by scripts/generate-baseline.js after a data collection run.
// Falls back to hardcoded values when baseline doesn't exist (first run or CI cold start).
const _baseline = (() => {
  try { return require('../reports/perf-baseline.json'); } catch (_) { return {}; }
})();
const budget = (key, fallback) => _baseline[key] != null ? _baseline[key] : fallback;

// Accumulated results written out in afterAll
let flatRevealResults = null;
let nestedRevealResults = null;
let unRevealResults = null;

// ---------------------------------------------------------------------------
// beforeAll — set blur_all: true and reveal_mode: 'hover' for all tests in
// this file. Both settings must be active before any page loads.
// ---------------------------------------------------------------------------
test.beforeAll(async ({ extSw }) => {
  await resetModel(extSw);
  await setModel(extSw, {
    blur_all: { status: true },
    settings: { reveal_mode: 'hover' },
  });
});

// ---------------------------------------------------------------------------
// Test 1: reveal latency on flat targets
//
// Target: .reveal-target elements (100 flat paragraphs on page-reveal.html)
// Iterations: 20 (reveal is fast — more iterations = better stats)
// Budget: p95 < 80ms
// ---------------------------------------------------------------------------
test('reveal: hover latency on flat targets', async ({ extContext, extSw, fixtureUrl }) => {
  const page = await extContext.newPage();
  await page.goto(fixtureUrl('reveal'), { waitUntil: 'load' });

  // Wait for elements to be blurred by the extension
  await page.waitForFunction(
    () => document.querySelectorAll('.bl-si-blurred').length > 20,
    { timeout: 15000 }
  );

  const durations = [];

  // Stamp each target with data-perf-idx and collect bounding boxes.
  // data-perf-idx gives a reliable selector regardless of sibling structure
  // (nth-child would match position among all siblings, not class members).
  const boxes = await page.evaluate(() => {
    return Array.from(document.querySelectorAll('.reveal-target')).slice(0, 20).map((el, i) => {
      el.setAttribute('data-perf-idx', i);
      const r = el.getBoundingClientRect();
      return { x: r.left + r.width / 2, y: r.top + r.height / 2 };
    });
  });

  for (let i = 0; i < 20; i++) {
    const box = boxes[i % boxes.length];
    const elemIdx = i % 20;
    const sel = `[data-perf-idx="${elemIdx}"]`;

    // Move mouse away first to reset any existing reveal state
    await page.mouse.move(0, 0);
    await page.waitForTimeout(100);

    // Verify the attribute is NOT present before hover (diagnostic only)
    void await page.evaluate((idx) => {
      const el = document.querySelectorAll('.reveal-target')[idx];
      return el ? el.hasAttribute('data-bl-si-reveal') : null;
    }, elemIdx);

    // Start waiting for attribute BEFORE triggering the hover — timing starts here
    const measurePromise = waitForAttr(page, sel, 'data-bl-si-reveal', { timeout: 5000 });
    await page.mouse.move(box.x, box.y);

    try {
      const result = await measurePromise;
      durations.push(result.durationMs);
    } catch (e) {
      console.warn(`[reveal:flat] iteration ${i} timed out — skipping`);
    }

    await page.waitForTimeout(100);
  }

  const stats = summarize(durations);
  console.log(
    `[reveal:hover-flat] p50=${stats.p50}ms p95=${stats.p95}ms max=${stats.max}ms n=${stats.n}`
  );

  expect(stats.p95).toBeLessThan(budget('reveal.flat.p95_ms', 80));
  // At least 15 of 20 iterations must succeed
  expect(stats.n).toBeGreaterThanOrEqual(15);

  flatRevealResults = { target: 'flat', iterations: 20, durations, stats };

  await page.close();
});

// ---------------------------------------------------------------------------
// Test 2: reveal latency on nested groups
//
// Target: .nested-group p elements (3-level nested: article > section > p)
// Tests ancestor/descendant cascade in the reveal controller.
// Iterations: 10 (20 groups × cycling through first 10)
// Budget: p95 < 120ms (ancestor chain traversal adds overhead)
// ---------------------------------------------------------------------------
test('reveal: hover latency on nested groups', async ({ extContext, extSw, fixtureUrl }) => {
  const page = await extContext.newPage();
  await page.goto(fixtureUrl('reveal'), { waitUntil: 'load' });

  // Wait for elements to be blurred by the extension
  await page.waitForFunction(
    () => document.querySelectorAll('.bl-si-blurred').length > 20,
    { timeout: 15000 }
  );

  const durations = [];

  // Stamp each nested target with data-perf-idx and collect bounding boxes.
  const boxes = await page.evaluate(() => {
    return Array.from(document.querySelectorAll('.nested-group p')).slice(0, 10).map((el, i) => {
      el.setAttribute('data-perf-idx', i);
      const r = el.getBoundingClientRect();
      return { x: r.left + r.width / 2, y: r.top + r.height / 2 };
    });
  });

  for (let i = 0; i < 10; i++) {
    const box = boxes[i % boxes.length];
    const elemIdx = i % 10;
    const nthChildSel = `[data-perf-idx="${elemIdx}"]`;

    // Move mouse away first to reset any existing reveal state
    await page.mouse.move(0, 0);
    await page.waitForTimeout(100);

    // Verify the attribute is NOT present before hover (diagnostic only)
    void await page.evaluate((idx) => {
      const el = document.querySelectorAll('.nested-group p')[idx];
      return el ? el.hasAttribute('data-bl-si-reveal') : null;
    }, elemIdx);

    // Start waiting for attribute BEFORE triggering the hover — timing starts here
    const measurePromise = waitForAttr(page, nthChildSel, 'data-bl-si-reveal', { timeout: 5000 });
    await page.mouse.move(box.x, box.y);

    try {
      const result = await measurePromise;
      durations.push(result.durationMs);
    } catch (e) {
      console.warn(`[reveal:nested] iteration ${i} timed out — skipping`);
    }

    await page.waitForTimeout(100);
  }

  const stats = summarize(durations);
  console.log(
    `[reveal:hover-nested] p50=${stats.p50}ms p95=${stats.p95}ms max=${stats.max}ms n=${stats.n}`
  );

  // Ancestor chain traversal is more expensive — higher budget
  expect(stats.p95).toBeLessThan(budget('reveal.nested.p95_ms', 120));
  // At least 8 of 10 iterations must succeed
  expect(stats.n).toBeGreaterThanOrEqual(8);

  nestedRevealResults = { target: 'nested', iterations: 10, durations, stats };

  await page.close();
});

// ---------------------------------------------------------------------------
// Test 3: un-reveal (mouseout) latency
//
// After hovering to reveal, measure how long it takes to un-reveal after
// moving the mouse away (mouseout event).
// Iterations: 10
// Budget: p95 < 80ms
// ---------------------------------------------------------------------------
test('reveal: un-reveal (mouseout) latency', async ({ extContext, extSw, fixtureUrl }) => {
  const page = await extContext.newPage();
  await page.goto(fixtureUrl('reveal'), { waitUntil: 'load' });

  // Wait for elements to be blurred by the extension
  await page.waitForFunction(
    () => document.querySelectorAll('.bl-si-blurred').length > 20,
    { timeout: 15000 }
  );

  const durations = [];

  // Stamp each target with data-perf-idx and collect bounding boxes.
  const boxes = await page.evaluate(() => {
    return Array.from(document.querySelectorAll('.reveal-target')).slice(0, 10).map((el, i) => {
      el.setAttribute('data-perf-idx', i);
      const r = el.getBoundingClientRect();
      return { x: r.left + r.width / 2, y: r.top + r.height / 2 };
    });
  });

  for (let i = 0; i < 10; i++) {
    const box = boxes[i % boxes.length];
    const elemIdx = i % 10;
    const selector = `[data-perf-idx="${elemIdx}"]`;

    // Move mouse away first to ensure a clean state
    await page.mouse.move(0, 0);
    await page.waitForTimeout(100);

    // Hover to reveal the element
    await page.mouse.move(box.x, box.y);

    // Wait until data-bl-si-reveal appears before starting the un-reveal measurement
    try {
      await page.waitForFunction(
        (sel) => document.querySelector(sel) !== null && document.querySelector(sel).hasAttribute('data-bl-si-reveal'),
        selector,
        { timeout: 5000 }
      );
    } catch (e) {
      console.warn(`[reveal:un-reveal] iteration ${i} — reveal did not appear, skipping`);
      await page.mouse.move(0, 0);
      await page.waitForTimeout(100);
      continue;
    }

    // Now measure: how long until data-bl-si-reveal is REMOVED after mouseout
    const t0 = await page.evaluate(() => performance.now());
    await page.mouse.move(0, 0);

    try {
      await page.waitForFunction(
        (sel) => {
          const el = document.querySelector(sel);
          return el === null || !el.hasAttribute('data-bl-si-reveal');
        },
        selector,
        { timeout: 5000 }
      );
      const dur = await page.evaluate((start) => Math.round(performance.now() - start), t0);
      durations.push(dur);
    } catch (e) {
      console.warn(`[reveal:un-reveal] iteration ${i} — un-reveal timed out, skipping`);
    }

    await page.waitForTimeout(100);
  }

  const stats = summarize(durations);
  console.log(
    `[reveal:un-reveal] p50=${stats.p50}ms p95=${stats.p95}ms max=${stats.max}ms n=${stats.n}`
  );

  expect(stats.p95).toBeLessThan(budget('reveal.un_reveal.p95_ms', 80));
  // At least 8 of 10 iterations must succeed
  expect(stats.n).toBeGreaterThanOrEqual(8);

  unRevealResults = { target: 'un-reveal', iterations: 10, durations, stats };

  await page.close();
});

// ---------------------------------------------------------------------------
// afterAll — write all three results to reports/05-reveal-raw.json
// ---------------------------------------------------------------------------
test.afterAll(async () => {
  const reportsDir = path.resolve(__dirname, '../reports');
  if (!fs.existsSync(reportsDir)) fs.mkdirSync(reportsDir, { recursive: true });

  fs.writeFileSync(
    path.join(reportsDir, '05-reveal-raw.json'),
    JSON.stringify(
      {
        timestamp: new Date().toISOString(),
        tests: [
          flatRevealResults ?? null,
          nestedRevealResults ?? null,
          unRevealResults ?? null,
        ],
      },
      null,
      2
    )
  );
});
